version: '3'

services:
  # The load balancer
  nginx:
    image: nginx:stable-alpine-perl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front_test/:/usr/share/nginx/html:ro
    ports:
      - "8080:8080"
